<?php

return [
    'token_refresh_ttl_minutes' => (int) env('INTEGRATIONS_TOKEN_REFRESH_TTL_MINUTES', 60),
    'feature_flags' => [
        'myid' => filter_var(env('INTEGRATIONS_MYID_ENABLED', false), FILTER_VALIDATE_BOOL),
        'eimzo' => filter_var(env('INTEGRATIONS_EIMZO_ENABLED', false), FILTER_VALIDATE_BOOL),
    ],
    'catalog' => [
        'email' => [
            'name' => 'Email',
            'category' => 'notifications',
            'default_enabled' => true,
            'supports' => [
                'credentials' => true,
                'health' => true,
                'logs' => true,
                'webhooks' => false,
                'tokens' => false,
                'test_connection' => true,
            ],
            'credential_fields' => [
                ['key' => 'mailer', 'label' => 'Mailer', 'secret' => false, 'required' => false],
                ['key' => 'host', 'label' => 'Host', 'secret' => false, 'required' => false],
                ['key' => 'port', 'label' => 'Port', 'secret' => false, 'required' => false],
                ['key' => 'username', 'label' => 'Username', 'secret' => false, 'required' => false],
                ['key' => 'password', 'label' => 'Password', 'secret' => true, 'required' => false],
            ],
        ],
        'telegram' => [
            'name' => 'Telegram Bot',
            'category' => 'notifications',
            'default_enabled' => true,
            'supports' => [
                'credentials' => true,
                'health' => true,
                'logs' => true,
                'webhooks' => true,
                'tokens' => false,
                'test_connection' => true,
            ],
            'credential_fields' => [
                ['key' => 'api_base_url', 'label' => 'API Base URL', 'secret' => false, 'required' => false],
                ['key' => 'bot_token', 'label' => 'Bot Token', 'secret' => true, 'required' => true],
                ['key' => 'webhook_secret', 'label' => 'Webhook Secret', 'secret' => true, 'required' => false],
            ],
            'webhook' => [
                'path' => '/api/v1/webhooks/telegram',
                'auth_mode' => 'secret_header',
                'rotate_supported' => true,
            ],
        ],
        'eskiz' => [
            'name' => 'Eskiz',
            'category' => 'sms',
            'default_enabled' => true,
            'supports' => [
                'credentials' => true,
                'health' => true,
                'logs' => true,
                'webhooks' => false,
                'tokens' => false,
                'test_connection' => true,
            ],
            'credential_fields' => [
                ['key' => 'api_key', 'label' => 'API Key', 'secret' => true, 'required' => true],
                ['key' => 'sender', 'label' => 'Sender', 'secret' => false, 'required' => false],
            ],
        ],
        'playmobile' => [
            'name' => 'Play Mobile',
            'category' => 'sms',
            'default_enabled' => true,
            'supports' => [
                'credentials' => true,
                'health' => true,
                'logs' => true,
                'webhooks' => false,
                'tokens' => false,
                'test_connection' => true,
            ],
            'credential_fields' => [
                ['key' => 'username', 'label' => 'Username', 'secret' => false, 'required' => true],
                ['key' => 'password', 'label' => 'Password', 'secret' => true, 'required' => true],
                ['key' => 'sender', 'label' => 'Sender', 'secret' => false, 'required' => false],
            ],
        ],
        'textup' => [
            'name' => 'TextUp',
            'category' => 'sms',
            'default_enabled' => true,
            'supports' => [
                'credentials' => true,
                'health' => true,
                'logs' => true,
                'webhooks' => false,
                'tokens' => false,
                'test_connection' => true,
            ],
            'credential_fields' => [
                ['key' => 'api_key', 'label' => 'API Key', 'secret' => true, 'required' => true],
                ['key' => 'sender', 'label' => 'Sender', 'secret' => false, 'required' => false],
            ],
        ],
        'payme' => [
            'name' => 'Payme',
            'category' => 'payments',
            'default_enabled' => true,
            'supports' => [
                'credentials' => true,
                'health' => true,
                'logs' => true,
                'webhooks' => false,
                'tokens' => false,
                'test_connection' => true,
            ],
            'credential_fields' => [
                ['key' => 'merchant_id', 'label' => 'Merchant ID', 'secret' => false, 'required' => true],
                ['key' => 'merchant_login', 'label' => 'Merchant Login', 'secret' => false, 'required' => true],
                ['key' => 'merchant_key', 'label' => 'Merchant Key', 'secret' => true, 'required' => true],
            ],
        ],
        'click' => [
            'name' => 'Click',
            'category' => 'payments',
            'default_enabled' => true,
            'supports' => [
                'credentials' => true,
                'health' => true,
                'logs' => true,
                'webhooks' => false,
                'tokens' => false,
                'test_connection' => true,
            ],
            'credential_fields' => [
                ['key' => 'merchant_id', 'label' => 'Merchant ID', 'secret' => false, 'required' => true],
                ['key' => 'service_id', 'label' => 'Service ID', 'secret' => false, 'required' => true],
                ['key' => 'merchant_user_id', 'label' => 'Merchant User ID', 'secret' => false, 'required' => false],
                ['key' => 'secret_key', 'label' => 'Secret Key', 'secret' => true, 'required' => true],
            ],
        ],
        'uzum' => [
            'name' => 'Uzum',
            'category' => 'payments',
            'default_enabled' => true,
            'supports' => [
                'credentials' => true,
                'health' => true,
                'logs' => true,
                'webhooks' => false,
                'tokens' => false,
                'test_connection' => true,
            ],
            'credential_fields' => [
                ['key' => 'service_id', 'label' => 'Service ID', 'secret' => false, 'required' => true],
                ['key' => 'merchant_login', 'label' => 'Merchant Login', 'secret' => false, 'required' => true],
                ['key' => 'merchant_password', 'label' => 'Merchant Password', 'secret' => true, 'required' => true],
            ],
        ],
        'mock-lab' => [
            'name' => 'Mock Lab',
            'category' => 'labs',
            'default_enabled' => true,
            'supports' => [
                'credentials' => true,
                'health' => true,
                'logs' => true,
                'webhooks' => true,
                'tokens' => false,
                'test_connection' => true,
            ],
            'credential_fields' => [
                ['key' => 'secret', 'label' => 'Webhook Secret', 'secret' => true, 'required' => true],
                ['key' => 'external_order_prefix', 'label' => 'External Order Prefix', 'secret' => false, 'required' => false],
            ],
            'webhook' => [
                'path' => '/api/v1/webhooks/lab/mock-lab',
                'auth_mode' => 'signature_header',
                'rotate_supported' => true,
            ],
        ],
        'myid' => [
            'name' => 'MyID',
            'category' => 'identity',
            'default_enabled' => false,
            'feature_flag' => 'myid',
            'supports' => [
                'credentials' => true,
                'health' => true,
                'logs' => true,
                'webhooks' => true,
                'tokens' => true,
                'test_connection' => true,
            ],
            'credential_fields' => [
                ['key' => 'client_id', 'label' => 'Client ID', 'secret' => false, 'required' => true],
                ['key' => 'client_secret', 'label' => 'Client Secret', 'secret' => true, 'required' => true],
                ['key' => 'token_endpoint', 'label' => 'Token Endpoint', 'secret' => false, 'required' => false],
                ['key' => 'access_token', 'label' => 'Access Token', 'secret' => true, 'required' => false],
                ['key' => 'refresh_token', 'label' => 'Refresh Token', 'secret' => true, 'required' => false],
                ['key' => 'access_token_expires_at', 'label' => 'Access Token Expires At', 'secret' => false, 'required' => false],
                ['key' => 'refresh_token_expires_at', 'label' => 'Refresh Token Expires At', 'secret' => false, 'required' => false],
                ['key' => 'token_type', 'label' => 'Token Type', 'secret' => false, 'required' => false],
                ['key' => 'scopes', 'label' => 'Scopes', 'secret' => false, 'required' => false],
            ],
            'webhook' => [
                'path' => '/api/v1/webhooks/myid',
                'auth_mode' => 'secret_header',
                'rotate_supported' => true,
            ],
        ],
        'eimzo' => [
            'name' => 'E-IMZO',
            'category' => 'identity',
            'default_enabled' => false,
            'feature_flag' => 'eimzo',
            'supports' => [
                'credentials' => true,
                'health' => true,
                'logs' => true,
                'webhooks' => true,
                'tokens' => true,
                'test_connection' => true,
            ],
            'credential_fields' => [
                ['key' => 'client_id', 'label' => 'Client ID', 'secret' => false, 'required' => true],
                ['key' => 'client_secret', 'label' => 'Client Secret', 'secret' => true, 'required' => true],
                ['key' => 'token_endpoint', 'label' => 'Token Endpoint', 'secret' => false, 'required' => false],
                ['key' => 'access_token', 'label' => 'Access Token', 'secret' => true, 'required' => false],
                ['key' => 'refresh_token', 'label' => 'Refresh Token', 'secret' => true, 'required' => false],
                ['key' => 'access_token_expires_at', 'label' => 'Access Token Expires At', 'secret' => false, 'required' => false],
                ['key' => 'refresh_token_expires_at', 'label' => 'Refresh Token Expires At', 'secret' => false, 'required' => false],
                ['key' => 'token_type', 'label' => 'Token Type', 'secret' => false, 'required' => false],
                ['key' => 'scopes', 'label' => 'Scopes', 'secret' => false, 'required' => false],
            ],
            'webhook' => [
                'path' => '/api/v1/webhooks/eimzo',
                'auth_mode' => 'secret_header',
                'rotate_supported' => true,
            ],
        ],
    ],
];
